version: 2
jobs:
  docker_backend_build:
    working_directory: /server
    environment:
      IMAGE_NAME: faithkovi/t24-server
    docker:
    # circleci node image that contains binaries and tools required for the build.
      - image: cimg/node:10.19.0

    steps:
    # This allocates a new docker engine that is separate from the environment that is running our job.
      - checkout
      - setup_remote_docker
      - deploy:
          name: Push to docker hub
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker image push $IMAGE_NAME:v1

  docker_frontend_build:
    working_directory: /client
    environment:
      IMAGE_NAME: faithkovi/t24-client
    docker:
    # circleci node image that contains binaries and tools required for the build.
      - image: cimg/node:14.8.0-alpine3.12

    steps:
    # This allocates a new docker engine that is separate from the environment that is running our job.
      - checkout
      - setup_remote_docker

      - deploy:
          name: Push to docker hub
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker image push $IMAGE_NAME:v1

workflows:
  version: 2
  build_docker_image:
    jobs:
      - docker_backend_build
      - docker_frontend_build
