version: "3"
services:
  mongodb:
    container_name: mongo-con
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGODB_CONNSTRING= 'mongodb+srv://dbtest:test1234@cluster0.ppfwj.mongodb.net/dbtest?retryWrites=true&w=majority'


